//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonLib.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommonLib.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active groups fetched successfully.
        /// </summary>
        public static string ActiveGroupsFetchedSuccessfully {
            get {
                return ResourceManager.GetString("ActiveGroupsFetchedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while fetching active groups.
        /// </summary>
        public static string ActiveGroupsFetchError {
            get {
                return ResourceManager.GetString("ActiveGroupsFetchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active merchants fetched successfully.
        /// </summary>
        public static string ActiveMerchantsFetchedSuccessfully {
            get {
                return ResourceManager.GetString("ActiveMerchantsFetchedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while fetching active merchants.
        /// </summary>
        public static string ActiveMerchantsFetchError {
            get {
                return ResourceManager.GetString("ActiveMerchantsFetchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during login.
        /// </summary>
        public static string Anerroroccurredduringlogin {
            get {
                return ResourceManager.GetString("Anerroroccurredduringlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch created successfully.
        /// </summary>
        public static string Branchcreatedsuccessfully {
            get {
                return ResourceManager.GetString("Branchcreatedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating the branch.
        /// </summary>
        public static string BranchCreationError {
            get {
                return ResourceManager.GetString("BranchCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch deleted successfully.
        /// </summary>
        public static string Branchdeletedsuccessfully {
            get {
                return ResourceManager.GetString("Branchdeletedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting branch.
        /// </summary>
        public static string BranchDeletionError {
            get {
                return ResourceManager.GetString("BranchDeletionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All branches fetched successfully.
        /// </summary>
        public static string BranchesFetchedSuccessfully {
            get {
                return ResourceManager.GetString("BranchesFetchedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while fetching branches.
        /// </summary>
        public static string BranchesFetchError {
            get {
                return ResourceManager.GetString("BranchesFetchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch updated successfully.
        /// </summary>
        public static string Branchupdatedsuccessfully {
            get {
                return ResourceManager.GetString("Branchupdatedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating branch with ID: {0}.
        /// </summary>
        public static string BranchUpdateError {
            get {
                return ResourceManager.GetString("BranchUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error changing merchant group for merchant id.
        /// </summary>
        public static string Errorchangingmerchantgroupformerchantid {
            get {
                return ResourceManager.GetString("Errorchangingmerchantgroupformerchantid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating branch.
        /// </summary>
        public static string Errorcreatingbranch {
            get {
                return ResourceManager.GetString("Errorcreatingbranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating group.
        /// </summary>
        public static string ErrorCreatingGroup {
            get {
                return ResourceManager.GetString("ErrorCreatingGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating merchant with Name.
        /// </summary>
        public static string Errorcreatingmerchantwithname {
            get {
                return ResourceManager.GetString("Errorcreatingmerchantwithname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating merchant with Name.
        /// </summary>
        public static string Errorcreatingmerchantwiththisname {
            get {
                return ResourceManager.GetString("Errorcreatingmerchantwiththisname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting branch.
        /// </summary>
        public static string Errordeletingbranchwithid {
            get {
                return ResourceManager.GetString("Errordeletingbranchwithid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting group.
        /// </summary>
        public static string ErrorDeletingGroup {
            get {
                return ResourceManager.GetString("ErrorDeletingGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Fetching Active Groups.
        /// </summary>
        public static string ErrorFetchingActiveGroups {
            get {
                return ResourceManager.GetString("ErrorFetchingActiveGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error fetching active merchants.
        /// </summary>
        public static string Errorfetchingactivemerchants {
            get {
                return ResourceManager.GetString("Errorfetchingactivemerchants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Fetching All Branches.
        /// </summary>
        public static string ErrorFetchingAllBranches {
            get {
                return ResourceManager.GetString("ErrorFetchingAllBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Fetching All Groups.
        /// </summary>
        public static string ErrorFetchingAllGroups {
            get {
                return ResourceManager.GetString("ErrorFetchingAllGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error fetching main branch for merchant id.
        /// </summary>
        public static string Errorfetchingmainbranchformerchantid {
            get {
                return ResourceManager.GetString("Errorfetchingmainbranchformerchantid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error fetching merchant details for id.
        /// </summary>
        public static string Errorfetchingmerchantdetailsforid {
            get {
                return ResourceManager.GetString("Errorfetchingmerchantdetailsforid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error fetching merchants by group id.
        /// </summary>
        public static string Errorfetchingmerchantsbygroupid {
            get {
                return ResourceManager.GetString("Errorfetchingmerchantsbygroupid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error fetching merchant with branches for id.
        /// </summary>
        public static string Errorfetchingmerchantwithbranchesforid {
            get {
                return ResourceManager.GetString("Errorfetchingmerchantwithbranchesforid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error generating PDF for search with parameters.
        /// </summary>
        public static string ErrorgeneratingPDFforsearchwithparameters {
            get {
                return ResourceManager.GetString("ErrorgeneratingPDFforsearchwithparameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error generating PDF with branches for search with parameters.
        /// </summary>
        public static string ErrorgeneratingPDFwithbranchesforsearchwithparameters {
            get {
                return ResourceManager.GetString("ErrorgeneratingPDFwithbranchesforsearchwithparameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error searching merchants with parameters.
        /// </summary>
        public static string Errorsearchingmerchantswithparameters {
            get {
                return ResourceManager.GetString("Errorsearchingmerchantswithparameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating branch.
        /// </summary>
        public static string Errorupdatingbranchwithid {
            get {
                return ResourceManager.GetString("Errorupdatingbranchwithid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating group name.
        /// </summary>
        public static string ErrorUpdatingGroupName {
            get {
                return ResourceManager.GetString("ErrorUpdatingGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating merchant details for merchant id.
        /// </summary>
        public static string Errorupdatingmerchantdetailsformerchantid {
            get {
                return ResourceManager.GetString("Errorupdatingmerchantdetailsformerchantid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group created successfully.
        /// </summary>
        public static string GroupCreatedSuccessfully {
            get {
                return ResourceManager.GetString("GroupCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating the group.
        /// </summary>
        public static string GroupCreationError {
            get {
                return ResourceManager.GetString("GroupCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group deleted successfully.
        /// </summary>
        public static string GroupDeletedSuccessfully {
            get {
                return ResourceManager.GetString("GroupDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting group with ID: {0}.
        /// </summary>
        public static string GroupDeletionError {
            get {
                return ResourceManager.GetString("GroupDeletionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name updated successfully.
        /// </summary>
        public static string GroupNameUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("GroupNameUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating group name for ID: {0}.
        /// </summary>
        public static string GroupNameUpdateError {
            get {
                return ResourceManager.GetString("GroupNameUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All groups fetched successfully.
        /// </summary>
        public static string GroupsFetchedSuccessfully {
            get {
                return ResourceManager.GetString("GroupsFetchedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while fetching groups.
        /// </summary>
        public static string GroupsFetchError {
            get {
                return ResourceManager.GetString("GroupsFetchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group updated successfully.
        /// </summary>
        public static string GroupUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("GroupUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid language specified. Use &apos;ar&apos; or &apos;en&apos;.
        /// </summary>
        public static string InvalidLanguage {
            get {
                return ResourceManager.GetString("InvalidLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string Invalidusernameorpassword {
            get {
                return ResourceManager.GetString("Invalidusernameorpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during login.
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successful.
        /// </summary>
        public static string LoginSuccessful {
            get {
                return ResourceManager.GetString("LoginSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main branch fetched successfully.
        /// </summary>
        public static string MainBranchFetched {
            get {
                return ResourceManager.GetString("MainBranchFetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while fetching main branch for merchant ID: {0}.
        /// </summary>
        public static string MainBranchFetchError {
            get {
                return ResourceManager.GetString("MainBranchFetchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while fetching merchant branches for ID: {0}.
        /// </summary>
        public static string MerchantBranchesFetchError {
            get {
                return ResourceManager.GetString("MerchantBranchesFetchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant created successfully.
        /// </summary>
        public static string Merchantcreatedsuccessfully {
            get {
                return ResourceManager.GetString("Merchantcreatedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating the merchant.
        /// </summary>
        public static string MerchantCreationError {
            get {
                return ResourceManager.GetString("MerchantCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant details fetched successfully.
        /// </summary>
        public static string MerchantDetailsFetched {
            get {
                return ResourceManager.GetString("MerchantDetailsFetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while fetching details for merchant ID: {0}.
        /// </summary>
        public static string MerchantDetailsFetchError {
            get {
                return ResourceManager.GetString("MerchantDetailsFetchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant group changed successfully.
        /// </summary>
        public static string Merchantgroupchangedsuccessfully {
            get {
                return ResourceManager.GetString("Merchantgroupchangedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while changing merchant group for ID: {0}.
        /// </summary>
        public static string MerchantGroupChangeError {
            get {
                return ResourceManager.GetString("MerchantGroupChangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while fetching merchants for group ID: {0}.
        /// </summary>
        public static string MerchantsFetchByGroupError {
            get {
                return ResourceManager.GetString("MerchantsFetchByGroupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchants fetched for group ID successfully.
        /// </summary>
        public static string MerchantsFetchedByGroupId {
            get {
                return ResourceManager.GetString("MerchantsFetchedByGroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error generating PDF for merchants.
        /// </summary>
        public static string MerchantsPdfGenerationError {
            get {
                return ResourceManager.GetString("MerchantsPdfGenerationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while searching merchants.
        /// </summary>
        public static string MerchantsSearchError {
            get {
                return ResourceManager.GetString("MerchantsSearchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchants search results fetched successfully.
        /// </summary>
        public static string MerchantsSearchResults {
            get {
                return ResourceManager.GetString("MerchantsSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error generating PDF for merchants with branches.
        /// </summary>
        public static string MerchantsWithBranchesPdfGenerationError {
            get {
                return ResourceManager.GetString("MerchantsWithBranchesPdfGenerationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant updated successfully.
        /// </summary>
        public static string Merchantupdatedsuccessfully {
            get {
                return ResourceManager.GetString("Merchantupdatedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating merchant details for ID: {0}.
        /// </summary>
        public static string MerchantUpdateError {
            get {
                return ResourceManager.GetString("MerchantUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant with branches fetched successfully.
        /// </summary>
        public static string MerchantWithBranchesFetched {
            get {
                return ResourceManager.GetString("MerchantWithBranchesFetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during registration.
        /// </summary>
        public static string RegistrationError {
            get {
                return ResourceManager.GetString("RegistrationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration failed.
        /// </summary>
        public static string Registrationfailed {
            get {
                return ResourceManager.GetString("Registrationfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists.
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username and Password are required.
        /// </summary>
        public static string UsernameandPasswordarerequired {
            get {
                return ResourceManager.GetString("UsernameandPasswordarerequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username, Password, and Email are required.
        /// </summary>
        public static string UsernamePasswordAndEmailRequired {
            get {
                return ResourceManager.GetString("UsernamePasswordAndEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User registered successfully.
        /// </summary>
        public static string Userregisteredsuccessfully {
            get {
                return ResourceManager.GetString("Userregisteredsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation error: Please fill in all required fields.
        /// </summary>
        public static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
    }
}
