<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BaselineTypeDiscovery" Version="2.0.0" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="DinkToPdf" Version="1.0.8" />
    <PackageReference Include="FluentNHibernate" Version="3.4.1" />
    <PackageReference Include="libwkhtmltox-64" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="8.0.18" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.6" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.12.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="NHibernate" Version="5.5.2" />
    <PackageReference Include="Oracle.ManagedDataAccess" Version="23.9.0" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.9.0" />
    <PackageReference Include="StackExchange.Redis" Version="2.8.41" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.12.1" />
    <PackageReference Include="System.Resources.ResourceManager" Version="4.3.0" />
  </ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\DataLib\DataLib.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Resources\Resource.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Resource.resx</DependentUpon>
	  </Compile>
	  <Compile Update="Resources\Resources.en-US.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Resources.en-US.resx</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Update="Resources\Resource.resx">
	    <Generator>ResXFileCodeGenerator</Generator>
	    <LastGenOutput>Resource.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Resources\Resources.en-US.resx">
	    <Generator>ResXFileCodeGenerator</Generator>
	    <LastGenOutput>Resources.en-US.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Resources\Res.ar.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Res.ar.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Resources\Resources.ar-SA.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Res.ar.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

</Project>
